#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
# pgrep -x polybar > /dev/null || polybar &
$HOME/.config/polybar/launch.sh
setxkbmap us -variant alt-intl
xrandr --output DP-4 --mode 5120x1440 --rate 120
feh --bg-scale ~/Stockages/Wallpaper/wallhaven-2yxp16_5120x1440.png &
picom &

bspc monitor -d I II III IV V 

bspc config border_width            2
bspc config window_gap             12
bspc config focused_border_color "#d20f39"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme	longest_side 

bspc rule -a Alacritty desktop='^1'
bspc rule -a inkdrop desktop='^2' 
bspc rule -a firefox desktop='^2'  
bspc rule -a 1password desktop='^1' focus=on
bspc rule -a solaar desktop='^1' focus=on

pgrep -x alacritty > /dev/null || alacritty &
pgrep -x inkdrop > /dev/null || inkdrop &
pgrep -x firefox > /dev/null || firefox &
pgrep -x 1password > /dev/null || 1password &
bspc node -c
pgrep -x solaar > /dev/null || solaar &
bspc node -c




